version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: # Install the AWS CLI if it is not already included in the docker image
            name: Install awscli
            command: pip install awscli
      - run: # Deploy to S3 using the sync command
          name: Deploy to S3
          command: aws s3 sync build s3://pycircleci
          # --exclude "*" --include "*" --debug

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master